travis:
  secure:
    BINSTAR_TOKEN: U2ate1U7tgWR6WAtjQLXC8tucHTM2IqI07Gk6O6gUHwNQuNJhuQw2inAsOLP959bYu6y2AjMVJxmjqhFHCMGb0w0pMu5Z9H+C0agX/l4GK9iAWcMlcBGJ6BbrNGx7XMO5Xw2v43wVMVLgVh9VnFttii5YbnjJrlKch2iCxjXalAU8YvlNWvjht75ceZUwNWHXGlLFe0cwAvz/r89o3IAHBioUT5fvtZRjmZfsNFCuYOxI6cIH57aBHzoavnLITLxmEq5MWUzOMElgLmGQBnKp1du9LJyv3i3b6LSff7fqS5gsRFhhL5tp9lKNJrE1+NLg/2Gku+yRxDf6LgG8EFqodgGreOIKSdvXVVie+CD4fw146PW29b7SAMioRet9RFf8xXzsk1gKpT69JFpJgLVJcki06TBKBfVRWUqXb843OYBlwKKekKPt10RKzHApbPAMz3LOZtA10Z/8U+6PctsS6DKsle/mKhp01abfBl+UpYVPSC6SDecjvx0E9WOAMaFuogA+AtCgYkQCGLTKWNr6TrDVhOM7sYPPnaOW0HzOV0JGx+lchYn7+qzMnbTCZW/KY36c7zSmihCY6byf6lBOTxQ3Imj/uPmukQDJXy3NFGxfJX+cUQtHx+tPUPSLbNjUiXCI4HQgUENjjIO9513ih4W3L9/xPePrRO0sGboYv4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
