travis:
  secure:
    BINSTAR_TOKEN: M7TI3G6FaKunYSsoPiMDsVIwnTzI6AQ8ZdG0ZPZA+PJJniiO1ImJy8nft1micJwh0FlqYkfdF0uHonsq48M2mSp/H/oeeqDs1JPTQGXPiVW4mFy/nx8M9l15rOPE1sp+lwj5fIi0xNt+qqbgC+7owFjk2AMxBZLC+6QlsG/kyCNvdH8vv1x/PkLjgyD2A/BiaB+c31KwT2qOiusIJAQLPaYoGo+X6xoN2LOpvIRVwWvD7pBTeKenlT94q1l0BODBphPMm1MteNkvzCBmNlFNRWjIlvdeJFLEDx0sZS0OtfkDYVPuMBITPTDhVr3iq4LJWeemXpQ7KnXApcjiJiC1QHV5hPncTkYXOWaTeHqYYrTJtDgAcVsaVo/C3G/TP92J3puy3hYMB/TZFj1Hi2jj30rEQ97aXEFhT/lWuf0RsaixshpMl/7FrANv+bHKzjfhwASnmtZI6a/XHkMhgOzxVHc8teBQPc/61BhpWSkIQWnHkSvVQzxeJpcxiDGKX5uZO1BolXTlmfHQEkLlG+AaYrh0ZTAzoTPWJM+/jod8Q0Z/mvoRSNNm0ycSWxlQImOFCpPkel7XrN7xg18Ivo687ePbaTZ41vBvGDdmEDjjTCj+CMle5lPZZNghd59CMO6SYYgYx1rE6TlPgDFZwGtR/jJxzq0tROoV2RlCqieJZhs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
